### ISSUE TITLE
Seed needs a predefined type

### ISSUE THREAD

**Issue by thomas-nixon-baseline** [raisenational/serverless-dynamodb#47] opened 2024-03-14 01:42 UTC
Seed needs a type as it is being reported as an issue with Serverless Doctor.
https://github.com/raisenational/serverless-dynamodb/blob/b1224a4b5ff374aff915fa78ee6863dda05b13a2/src/index.ts#L143

Running serverless-offline shows
```
1 deprecation found: run 'serverless doctor' for more details
```

Running the doctor
```
$ npx serverless doctor
1 deprecation triggered in the last command:

CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
 - ServerlessDynamoDBPlugin for "seed"
Please report this issue in plugin issue tracker.
Starting with next major release, this will be communicated with a thrown error.
More info: https://serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA_V3
```

After making the change locally I found there was no longer a reported issue.

**Comment by domdomegg** [comment] 2024-03-16 21:10
Thanks for reporting this! I think this is a duplicate of #24

This is an upstream serverless limitation: https://github.com/serverless/serverless/issues/12217

You can ignore this error for now. When serverless v4 is released this plugin will be fixed.

**Closed as not planned by domdomegg** 2024-03-16 21:09 UTC
